### ISSUE TITLE
Can't install on Ruby 3

### ISSUE THREAD

**Issue by sandbergja** [ebsco/edsapi-ruby#112]
I am looking to see what all breaks in my app under Ruby 3. :-)

This is one of the things that breaks!  I didn't dig much, but it looks like there hasn't been a release of net-http-persistent that is compatible with Ruby 3 yet (https://github.com/drbrain/net-http-persistent/issues/123).

Adding this ticket in case it is helpful for tracking this and any other Ruby 3 compatibility issues.

**Comment by mjgiarlo** [comment]
@sandbergja Thanks for writing this issue up; the edsapi-ruby gem is currently preventing us from moving some of our codebases to Ruby 3, too. FYI: https://github.com/ebsco/edsapi-ruby/pull/113

**Comment by mmabrahamson** [comment]
Addressed in #114 and live now.
