### ISSUE TITLE
convert eds_authors to an array

### ISSUE THREAD

**Issue by bmckinney** [ebsco/edsapi-ruby#41]
can we get `eds_authors` as an `Array` -- it seems to be semi-colon delimited `String` right now? `eds_authors: Jannoura, Ramia; Joergensen, Rainer Georg; Bruns, Christian`

**Comment by drh-stanford** [comment]
i got this working with the 0.1.9 release so you can close this issue. thanks

**Comment by bmckinney** [comment]
see: https://github.com/ebsco/edsapi-ruby/commit/532b6ee41dbc5d66c0a4c4bfb7339c0e4499a483
