### ISSUE TITLE
author linked search - phrase search fails

### ISSUE THREAD

**Issue by bmckinney** [ebsco/edsapi-ruby#45]
Question about author linked searches:  when the author name has a role term following it, a phrase search fails.  e.g. edsswe__edsswe_oai_DiVA_org_liu_134775  A keyword search gets results, but more than it should.  Is there a separate index we should be looking at here? I notice the native UI doesn't link these authors.

**Comment by bmckinney** [comment]
Note: available in two databases: edsgao__edsgcl_476314180 and edsswe__edsswe_oai_DiVA_org_liu_134775.

The second one has author affiliations and roles within the author section.

**Comment by drh-stanford** [comment]
Duplicate of https://github.com/ebsco/edsapi-ruby/issues/51?

**Comment by ellieebsco** [comment]
Closing, see note in https://github.com/ebsco/edsapi-ruby/issues/51
