### ISSUE TITLE
CreateSession being called between searches

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#46]
@bmckinney Below is the network traffic when going to a display page -- note that we already have a session -- we do a Retrieve to get the metadata for the current record and then 2 searches (3?) to find the ID values for the previous and next records.

The problem here is that a `CreateSession` is being called between the Retrieve and the Search -- this is unexpected behavior.

```
DO_REQUEST: PATH: /authservice/rest/uidauth PAYLOAD: { ... }
DO_REQUEST: PATH: /edsapi/rest/Info PAYLOAD: null
DO_REQUEST: PATH: /edsapi/rest/Retrieve PAYLOAD: { ... }
DO_REQUEST: PATH: /authservice/rest/uidauth PAYLOAD: { ... }
DO_REQUEST: PATH: /edsapi/rest/Info PAYLOAD: null
DO_REQUEST: PATH: /edsapi/rest/CreateSession?profile=edsapi&guest=y&displaydatabasename=y PAYLOAD: null
DO_REQUEST: PATH: /edsapi/rest/Info PAYLOAD: null
DO_REQUEST: PATH: /edsapi/rest/Search PAYLOAD: { ... }
DO_REQUEST: PATH: /edsapi/rest/Search PAYLOAD: { ... }
DO_REQUEST: PATH: /edsapi/rest/Search PAYLOAD: { ... }
```

**Comment by drh-stanford** [comment]
I'm still seeing similar behavior in 0.2.9.pre. How often should the gem be calling CreateSession? i.e., is there an expire time for a session?

Sometimes I get the expected behavior:

```
I, [2017-08-03T12:52:24.859587 #10960]  INFO -- : POST https://eds-api.ebscohost.com/authservice/rest/uidauth
I, [2017-08-03T12:52:25.023239 #10960]  INFO -- : GET https://eds-api.ebscohost.com/edsapi/rest/Info
I, [2017-08-03T12:52:25.267884 #10960]  INFO -- : POST https://eds-api.ebscohost.com/edsapi/rest/Search
```

Other times I get a CreateSession

```
I, [2017-08-03T12:37:33.475550 #10076]  INFO -- : POST https://eds-api.ebscohost.com/authservice/rest/uidauth
I, [2017-08-03T12:37:33.632681 #10076]  INFO -- : GET https://eds-api.ebscohost.com/edsapi/rest/Info
I, [2017-08-03T12:37:33.826444 #10076]  INFO -- : GET https://eds-api.ebscohost.com/edsapi/rest/CreateSession?displaydatabasename=y&guest=n&profile=edsapi
I, [2017-08-03T12:37:34.124077 #10076]  INFO -- : GET https://eds-api.ebscohost.com/edsapi/rest/Info
I, [2017-08-03T12:37:34.321884 #10076]  INFO -- : POST https://eds-api.ebscohost.com/edsapi/rest/Search
```

**Comment by JPrevost** [comment]
Unrelated to this gem, but in general with the EDS API, we are seeing invalid sessions _a lot_.

Field engineers have replicated the sporadic problem. It may have nothing to do with this Issue, but it's possible this gem is masking the upstream bug by creating a new session when the bug manifests.

**Comment by efrierson** [comment]
Looks like this was related to an API session manager issue we had back in the day.  LMK if this still appears to be an issue - we've monitored traffic on successive calls and no longer see this in our gem.  Feel free to re-open if you continue to experience it.
