### ISSUE TITLE
EBSCO::EDS::BadRequest: Max Record Retrieval Exceeded

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#47]
@bmckinney When, for example, going to Page 4 with 100 per page, like so:

http://localhost:3000/article?page=4&per_page=100&q=tiger+conservation&search_field=search

we always get the following exception:

```
{"DetailedErrorDescription"=>"Requested records starting at # 301. Max start request number is : 251 ", 
 "ErrorDescription"=>"Max Record Retrieval Exceeded", 
 "ErrorNumber"=>"138"}
```

The expected behavior is to get results 301...400 from the search results.

**Comment by bmckinney** [comment]
same as: https://github.com/ebsco/edsapi-ruby/issues/10

**Comment by drh-stanford** [comment]
@bmckinney with the diagnosis being session-related I wonder if https://github.com/ebsco/edsapi-ruby/issues/46 is also a symptom of the same issue with the EDS service?

**Comment by drh-stanford** [comment]
@bmckinney it looks like 0.3.6.pre addresses this issue with the jump functionality. can you briefly describe the fix/workaround? is it pinning to a specific host to avoid the session misses?

**Comment by bmckinney** [comment]
The optional list of hosts is a temporary work around for a Service Issue. When the SI is resolved we'll notify you and this config property can be omitted, relying on the default host instead.
