### ISSUE TITLE
Authors have unstructured relator terms in them

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#51]
For example, this record `edsswe__edsswe_oai_DiVA_org_liu_134775` has:

```
Sovacool, Benjamin K., Author
Linköpings universitet, Institutionen för tema, Tema Miljöförändring, Originator
```

as its authors. We do linking for our rendering and we don't want the link to include these relator terms, like so:

![screen shot 2017-07-18 at 3 34 25 pm](https://user-images.githubusercontent.com/1861171/28342750-9d24992c-6bce-11e7-8f75-7dc0b0649d20.png)

Is there a way to (a) pass back structured data that allows us to identify the relator term, or (b) enumerate what the possible relator terms are so we can scrub the data?

**Comment by bmckinney** [comment]
see also: https://github.com/ebsco/edsapi-ruby/issues/45

**Comment by bmckinney** [comment]
@hectorcorrea is dealing with this as well: https://github.com/Brown-University-Library/bul-search/blob/master/app/models/eds_results.rb#L91

**Comment by ellieebsco** [comment]
It looks like the underlying data has been cleaned up for this record. 

Please reopen with a current example and I can see if this should be addressed through data clean up channels or within the gem. (@hectorcorrea, @drh-stanford)
