### ISSUE TITLE
Warning message in 0.2.9.pre

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#57]
I'm getting the following warning message:

```
ebsco-eds-0.2.9.pre/lib/ebsco/eds/session.rb:675: warning: regular expression has ']' without escape: /"Actions":\[]/
```

**Comment by bmckinney** [comment]
Yeah, showing my ruby inexperience at this point. RubyMine tells me that escaping the ']' is a 'Redundant character escape' so I skipped it. I'll add it back in for the next release.

**Comment by drh-stanford** [comment]
this is working in 0.3.0.pre. thanks
