### ISSUE TITLE
mechanisim for cleaning up the @cache_store

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#58]
0.2.9.pre includes caching of searches, but it's not clear to me how to cleanup expired files in the cache. The `ActiveSupport::Cache::Store` API has a `cleanup` method, but I don't see access to `@cache_store` external to the EDS API. 

Can we fire off a background thread the calls the `cleanup` method on `@cache_store` every few minutes? Maybe we can instantiate our own `FileStore` on the cache folder, but we don't know the actual cache folder external to the EDS API either AFAICT.

**Comment by bmckinney** [comment]
In a pinch you could cron: find $TMPDIR/faraday_eds_cache/ -mtime +1 -delete

**Comment by drh-stanford** [comment]
ok so we do know the cache folder.  i think that's fine for now.
