### ISSUE TITLE
Caching not session-specific

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#63]
We've been trying out the caching and it appears to be too aggressive. The session key should take into account the session key, or at least the guest mode state as part of the key.

The behavior we're seeing is that if a user logs in and issues the same search, the search is cached with the guest mode results, but the session has switched to non-guest mode. 

We'd expect the cache to get a miss when the session switches from guest to non-guest and vice versa.

**Comment by bmckinney** [comment]
Right, of course.

I'll try to automatically add the guest mode as part of the cache hash id.

**Comment by bmckinney** [comment]
see: 7a06ad224b47a6ef82ba341b0f6d604deed0c499
