### ISSUE TITLE
Add field to search results to indicate availability of HTML full text

### ISSUE THREAD

**Issue by bmckinney** [ebsco/edsapi-ruby#64]
A way during a Search to determine whether the `eds_html_fulltext` field will have data on a Retrieve. We'd like to mark whether there's HTML full text on the search results page.

**Comment by bmckinney** [comment]
From Eric:

You'll find a "1" in the Record[n].FullText.Text.Availability node if HTML full text is present.

**Comment by efrierson** [comment]
Sorry, I lied.  I have edited the comment to have the correct path.

**Comment by bmckinney** [comment]
see: f7d8f857015a07bce281c32b8435b7646661e954
