### ISSUE TITLE
Facets not properly escaped, result in 105 API errors

### ISSUE THREAD

**Issue by bmckinney** [ebsco/edsapi-ruby#65]
Example: "f":{"eds_content_provider_facet":["Business Insights: Essentials"]}

The colon needs to be escaped.

**Comment by efrierson** [comment]
Commas, Colons, and Parentheses need to be escaped with a backslash.  Here are a few more examples:

"f":{"eds_subjects_geographic_facet":["midwest (u.s.)"]}  - the parentheses need escaping
"f":{"eds_content_provider_facet":["Library, Information Science & Technology Abstracts"]} - the commas need escaping

**Comment by efrierson** [comment]
Please close issue https://github.com/sul-dlss/SearchWorks/issues/1619 when this is resolved.

**Comment by bmckinney** [comment]
This should be resolved as of 0.3.6.pre - Stanford should confirm.

**Comment by bmckinney** [comment]
old pattern: /(\'|\"|\*|\/|\\|\)|\$|\+|\(|\^|\?|\!|\~|\`|\:)/
new pattern: /([)(:,])/

see: c5eb511f30c7a5144efacd86572a04f22267cc4d
