### ISSUE TITLE
Indication of whether a fulltext link is a timebombed one

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#67]
Right now we're assuming *all* `pdf` and `ebook-pdf` fulltext links are time-bombed (expireable) URLs. It'd help to have that logic in the EDS gem and pass back a flag that indicates whether that URL expires and thus we need to hide it in our application.

**Comment by bmckinney** [comment]
At what point is this helpful? After issuing a search or after issuing a retrieve?

**Comment by drh-stanford** [comment]
Both. Right now, we're doing `link.href == 'detail'` to determine whether we have a time-bombed URL. I'd rather be able to do `link.expires?` or something to make this determination.

**Comment by bmckinney** [comment]
see: 9ae8b47356ae5b9b753506ea6160829a0f647700

**Comment by efrierson** [comment]
Closing issues that appear resolved.  Feel free to open if that is not the case!
