### ISSUE TITLE
Use IDs instead of labels when applying limiters and facets

### ISSUE THREAD

**Issue by bmckinney** [ebsco/edsapi-ruby#68]
To prevent saved URLs from breaking when labels are changed in Admin.

**Comment by jkeck** [comment]
FWIW, it might be a good idea to allow both.  The reason being that this will allow the limiters to be used as a standard facet by Blacklight as well as facilitate the custom implementation that we're working on.

**Comment by bmckinney** [comment]
see: 9ae8b47356ae5b9b753506ea6160829a0f647700
