### ISSUE TITLE
Add pubmed and sudoc IDs as record properties (like DOI property)

### ISSUE THREAD

**Issue by bmckinney** [ebsco/edsapi-ruby#69]

**Comment by efrierson** [comment]
If the data is in EDS API as a structured element, it will be pulled out here:  https://github.com/ebsco/edsapi-ruby/blob/a1350e827f47b77913e5eda0eaeb7ccae3e7f81c/lib/ebsco/eds/record.rb#L981

We have a unit test that demonstrates how SUDOC IDs might appear:  https://github.com/ebsco/edsapi-ruby/blob/a1350e827f47b77913e5eda0eaeb7ccae3e7f81c/test/record_test.rb#L218

If you're seeing the data appear in unexpected places or not seeing it on records you expect it, it's a data issue. issues can be submitted as enhancement requests to our primary support queue.  

Closing this, but please feel free to holler if you'd like us to follow up more on this.
