### ISSUE TITLE
Facet examples still giving "something went wrong" errors

### ISSUE THREAD

**Issue by jvine** [ebsco/edsapi-ruby#72]
https://sw-article-preview.stanford.edu/articles?f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&q=%22%E5%9C%B0%E6%96%B9%E6%94%BF%E5%BA%9C%22+%E6%94%B9%E9%9D%A9&search_field=search
Click on **Database** > China/Asia On Demand

https://sw-article-preview.stanford.edu/articles?f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&q=hearing+water+quality&search_field=search 
Click on **Publisher** > national archives & records service, office of the federal register

https://sw-article-preview.stanford.edu/articles?f%5Beds_language_facet%5D%5B%5D=english&f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&f%5Beds_subject_topic_facet%5D%5B%5D=avatar+%28film%29&q=film+review+avatar&search_field=search
Click on **Topic** > cameron, james, 1954-
(or any of the names with dates attached, in the Topic facet)

**Comment by drh-stanford** [comment]
The specific EDS error message is:

```
EBSCO::EDS::BadRequest: {"DetailedErrorDescription"=>"", "ErrorDescription"=>"Incorrect Number of Arguments", "ErrorNumber"=>"105"}
```

also see https://github.com/ebsco/edsapi-ruby/issues/65

**Comment by bmckinney** [comment]
add/remove in sanitize regex:

- don't escape slash
- escape commas

**Comment by jvine** [comment]
Is this case related to the character escaping issue?

https://sw-article-preview.stanford.edu/articles?f%5Beds_search_limiters_facet%5D%5B%5D=Stanford+has+it&q=children%27s+literature&search_field=search

Facet Topic > children's literature  shows  	280,420  but when you select it you get 3 results.

**Comment by efrierson** [comment]
Closing some older, resolved issues.  Looks like this has been resolved.  I tried each of the linked examples above (using the live deployment) and received expected results.  Please re-open if that is not the case!
