### ISSUE TITLE
searching subjects for -- delimited subjects seems not to work

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#76]
For example, this record `bas__BAS899713` has:

- `"Hong Kong -- Economics -- Economic Conditions"` 
- `"Hong Kong -- Anthropology & Sociology -- Social Conditions"`

as its subjects, but searching for those strings verbatim (and quoted) in a subject (`DE`) search yields no results. I've tried in the native UI for subject (`SU`) and nothing. If I do keyword (not sure of field code) in the basic search, it "works" in that I get some results. The native UI seems to use the `SH` field code for that 🤷‍♂️ 

When we do subject searches we use the descriptor field code. See https://github.com/sul-dlss/SearchWorks/blob/article-search/app/models/article_search_builder.rb#L16

**Comment by drh-stanford** [comment]
The suggestion is that we use the `<searchLink>` fieldCode data, but we're not seeing the `<searchLink>` metadata in the `eds_subjects` data:

![screen shot 2017-09-05 at 10 29 23 am](https://user-images.githubusercontent.com/1861171/30074109-18f0baf0-9225-11e7-9277-eb571f7a2786.png)

**Comment by bmckinney** [comment]
Should be fixed in 0.3.9.pre

**Comment by bmckinney** [comment]
Not done yet, we need to encode XML Text: <searchLink fieldCode=\"SH\" term=\"%22Hong+Kong+--+Philosophy+%26+Religion%22\">Philosophy & Religion</searchLink>
(&amp; instead of &)

**Comment by bmckinney** [comment]
Using sanitize now with a custom config: https://github.com/ebsco/edsapi-ruby/blob/master/lib/ebsco/eds/record.rb#L773-L783

**Comment by drh-stanford** [comment]
Is that released in a gem version?

**Comment by drh-stanford** [comment]
Here's an example where the subject has `<br>` markup but not `<searchLink>` markup:

https://searchworks.stanford.edu/articles/edswsc__000327490400066

```"eds_subjects": "Instruments &amp; Instrumentation<br>Nuclear Science &amp; Technology<br>Physics, Nuclear<br>Physics, Particles &amp; Fields<br>Instruments &amp; Instrumentation<br>Nuclear Science &amp; Technology<br>Physics",```

**Comment by efrierson** [comment]
Closing old issues that appear resolved.  The fix using `sanitize` was included in an earlier release of the gem, and the case of no `<searchLink>` markup was also addressed in another issue (https://github.com/ebsco/edsapi-ruby/issues/80).

Please re-open if this is not the case!
