### ISSUE TITLE
too many connection resets

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#78]
We're seeing the following error in production:

```
Faraday::TimeoutError: too many connection resets (due to execution expired - Net::OpenTimeout) after 0 requests on 70099183618440, last used 1505247344.7452774 seconds ago
```

It's happening during the session.search method.

**Comment by bmckinney** [comment]
You can try extending faraday's open timeout here: https://github.com/ebsco/edsapi-ruby/blob/master/lib/ebsco/eds/configuration.rb#L38

**Comment by drh-stanford** [comment]
We've been using 5 seconds. I'll try bumping it up to 10 seconds...

**Comment by bmckinney** [comment]
Thanks, let us know if that does the trick. You guys are the first to put this in production so we really had no baseline until now.

**Comment by efrierson** [comment]
Closing old issues that appear resolved.  Please re-open if this is not the case!
