### ISSUE TITLE
Question about capitalization of terms in facets

### ISSUE THREAD

**Issue by jvine** [ebsco/edsapi-ruby#79]
We are getting quite a lot of feedback about the lower-case facet values in some facets:

- language
- topic
- geography
- journal title
- publisher

a) Does Ebsco have any plans to restore lower-case terms to appropriate mixed case in the central index?
b) is there any light-weight way to apply this conversion on the fly when returning facets for a search? understanding that sometimes the outcome will be incorrect (like "Ieee" rather than "IEEE" for "ieee")

**Comment by bmckinney** [comment]
I'll investigate option b, @efrierson will get back to you on option a.

**Comment by efrierson** [comment]
Option A is to normalize the data we get from our varied providers. Some caps, some don't. :-/

titlize() may be as good as we can get. Bill, think the gem can caps it before it gets delivered? Maybe we can hard-code in some exceptions like IEEE? Maybe there would be too many of those..

In short, option A isn't feasible at this time, but I'll see if there's an enhancement request for this type of thing.

Brevity and typographical errors courtesy the tiny keyboard of a phone.

---
Eric Frierson
Director of Field Engineering, North America
EBSCO Information Services

On Sep 14, 2017, at 4:28 PM, bmckinney <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll investigate option b, @efrierson<https://github.com/efrierson> will get back to you on option a.

**Comment by bmckinney** [comment]
now available as of 0.3.16.pre, ability to specify an acronyms list: https://github.com/ebsco/edsapi-ruby/blob/master/lib/ebsco/eds/facet_titleize.rb#L6

**Comment by efrierson** [comment]
Closing old issues that appear resolved.  Please re-open if this is not the case!
