### ISSUE TITLE
subjects without searchLinks

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#80]
For example: `edswss__000306525900003`

The `eds_subjects` has the `<br>` markup but no `<searchLink>` markup.

```
eds_subjects: "DISTANCE-DECAY<br>WEB<br>INTERNET<br>INTELLIGENCE<br>GEOLOCATION<br>MODELS<br>GIS",
```

**Comment by bmckinney-ebsco** [comment]
Suggested fix is discussed here: https://github.com/sul-dlss/SearchWorks/issues/1791#issuecomment-329858666

**Comment by bmckinney-ebsco** [comment]
see: 889cdbbbf85b13330cd3e742431d01c9b9f805cc

**Comment by efrierson** [comment]
Bill's commit looks like it did the job.  Please re-open if that is not the case.
