### ISSUE TITLE
Select certain database facets and the date slider disappears

### ISSUE THREAD

**Issue by bmckinney** [ebsco/edsapi-ruby#83]
See: https://github.com/sul-dlss/SearchWorks/issues/1721

**Comment by bmckinney** [comment]
9/12 slack thread

Bill McKinney
is it possible for the date slider to be driven by just a max + min date instead of pub_year_tisim?

in reference to: https://github.com/sul-dlss/SearchWorks/issues/1721

Jessie Keck 
I think it would be technically possible, yeah. Are you thinking of returning that data somewhere else? And presumably the ability to query on that range would still be available?

Although the functionality is a bit custom, we are relying on patterns and functionality from the blacklight date range gem in the hopes that it could be used effectively out of the box one day (more of an FYI than anything). (

Bill McKinney
it seems that pub_year_tisim disappears when a database facet is applied (i need to consult with @ebscoeric on if we need to open a service issue on it) - however, the date_range should be available in all cases

btw, solr date range support is on our list

for date_range, see: https://github.com/ebsco/edsapi-ruby/blob/master/lib/ebsco/eds/results.rb#L525-L542

**Comment by efrierson** [comment]
Closing old issues.  This appears to be done.  Please re-open if not the case.
