### ISSUE TITLE
Some links are coming through without an http/https protocol

### ISSUE THREAD

**Issue by jkeck** [ebsco/edsapi-ruby#86]
Example record: eric__EJ1050530

This record comes through w/ the url value `eric.ed.gov?id=EJ1050530`

When constructing an html link w/ this, it gets treated as a relative URL by browsers.  We could try and capture for this type of thing on our end, but it would be nice if the data consistently included a protocol.

**Comment by bmckinney-ebsco** [comment]
```xml
    <FullText>
      <Text>
        <Availability>0</Availability>
      </Text>
      <CustomLinks>
        <CustomLink>
          <Url>eric.ed.gov?id=EJ1050530</Url>
          <Name>ERIC Full Text</Name>
          <Category>fullText</Category>
          <Text>Full Text from ERIC</Text>
        </CustomLink>
      </CustomLinks>
    </FullText>
```

**Comment by efrierson** [comment]
This is just a setting in EBSCOadmin.  I just switched it to HTTPS.  Holler if you want it changed again, but this isn’t a problem in the GEM.

—

Eric Frierson
Senior Director of Field Engineering, North America
EBSCO Information Services
efrierson@ebsco.com | 1-800-653-2726 x3548

**Comment by jkeck** [comment]
👍 I've confirmed w/ this record that the protocol is coming through now.  Thanks!
