### ISSUE TITLE
Possible to raise a specific error when a document is not found

### ISSUE THREAD

**Issue by jkeck** [ebsco/edsapi-ruby#88]
It would be great if we could easily differentiate between when we're getting a BadRequest error vs when the BadRequest is caused by a record not being found (so our app can properly show a 404 vs a 500 error page).

We're attempting to handle this locally by just rendering not found errors whenever a BadRequest error is thrown when requesting a record.  Not sure if a BadRequest error would ever get thrown for any other reason than the record was not found, but thought I would mention it just in case.

**Comment by efrierson** [comment]
Closing some of these older, seemingly resolved issues.  Please re-open if the merged work didn't actually resolve!
