### ISSUE TITLE
Error handling (+ a query that seems to always result in an error)

### ISSUE THREAD

**Issue by jkeck** [ebsco/edsapi-ruby#90]
I have been tracking down some errors that have happened in our site and noticed an area that could use some improvement from the gem.

In cases that an error is returned from the API, e.g. a response from the API that looks like:

<img width="454" alt="Screen Shot 2019-05-20 at 2 09 37 PM" src="https://user-images.githubusercontent.com/96776/58052159-f9a7f680-7b08-11e9-96c1-0efbca11db16.png">

The resulting HTML ends up as the value assigned to `@results` in the `Results` class. When this line is run it assumes a hash and throws a `NoMethodError` (this pattern appears several times in this class).
https://github.com/ebsco/edsapi-ruby/blob/404aae08ee0facd38cb5ce1916ac9bf28d2f6dfa/lib/ebsco/eds/results.rb#L49

I have noticed that any query with a boolean and a left and right hand numerical assignment causes this error to be thrown (e.g. `and 1=1`, `or 1=1`, `the meaning of life or 4=2`).  While I realize these aren't really legitimate queries to be running, they at least illustrate the case where the gem/api is throwing errors. 

There does appear to be cases where this happens during legitimate queries (at least intermittently) and handling these better at the gem level will make integrating w/ the gem more seamless.

Happy to help share any other debugging/thoughts to how to improve this if you all are interested.

**Comment by efrierson** [comment]
Closing some of these older, seemingly resolved issues.  Please re-open if the merged work didn't actually resolve!
