### ISSUE TITLE
RubyGems.org Ownership Incorrect

### ISSUE THREAD

**Issue by efrierson** [ebsco/edsapi-ruby#94]
@bmckinney-ebsco used to maintain the gem at RubyGems.org, but with his departure, I need to manage it.  Creating this issue per support ticket - https://help.rubygems.org/discussions/problems/37886-no-email-sent-with-either-activation-or-password-reset

**Comment by bmckinney** [comment]
Yes, I request to be removed and have @efrierson set as owner.

**Comment by efrierson** [comment]
You're the best, @bmckinney !!

**Comment by efrierson** [comment]
Testing

**Comment by efrierson** [comment]
I have temporarily moved this repo to my personal account to be the owner.  Will transfer it back to ebsco organization once the ownership change is made there.

**Comment by efrierson** [comment]
Whee! Done.
